"""Global fixtures for Nutrislice integration."""

from unittest.mock import patch

import pytest
import json
from custom_components.nutrislice.model import NutrisliceResponse

pytest_plugins = "pytest_homeassistant_custom_component"


@pytest.fixture(autouse=True)
def auto_enable_custom_integrations(enable_custom_integrations):
    """Enable custom integrations defined in the test dir."""
    yield


@pytest.fixture
def mock_setup_entry():
    """Override async_setup_entry."""
    with patch(
        "custom_components.nutrislice.async_setup_entry", return_value=True
    ) as mock_setup_entry:
        yield mock_setup_entry


# TODO: replace with real data from API
@pytest.fixture
def mock_nutrislice_data():
    """Return a standard Nutrislice API response."""
    return {
        "current_week": {
            "id": 12345,
            "start_date": "2026-02-16",
            "menu_type_id": 1,
            "last_updated": "2026-02-15T10:00:00Z",
            "bold_all_entrees_enabled": True,
            "days": [
                {
                    "date": "2026-02-16",
                    "has_unpublished_menus": False,
                    "menu_info": {},
                    "menu_items": [
                        {
                            "id": 100001,
                            "position": 1,
                            "is_section_title": False,
                            "bold": True,
                            "featured": False,
                            "is_holiday": True,
                            "text": "Presidents Day",
                            "food": None,
                            "category": "",
                            "menu_id": 99,
                            "no_line_break": False,
                            "blank_line": False,
                            "station_id": 0,
                            "is_station_header": False,
                            "station_is_collapsible": False,
                            "station_image_display_mode": "standard",
                            "image": "",
                            "image_thumbnail": "",
                            "serving_size_amount": None,
                            "serving_size_unit": None,
                            "smart_recipe_id": None,
                            "station_food_tags": [],
                            "food_variation_id": None,
                            "image_alt": None,
                            "image_description": None,
                            "price": None,
                        }
                    ],
                },
                {
                    "date": "2026-02-17",
                    "has_unpublished_menus": False,
                    "menu_info": {},
                    "menu_items": [
                        {
                            "id": 100002,
                            "position": 1,
                            "is_section_title": False,
                            "bold": False,
                            "featured": False,
                            "is_holiday": False,
                            "text": "",
                            "category": "entree",
                            "menu_id": 99,
                            "food": {
                                "id": 5001,
                                "name": "Pizza",
                                "description": "Cheese Pizza",
                                "subtext": "",
                                "image_url": None,
                                "food_category": "entree",
                                "rounded_nutrition_info": {},
                                "has_nutrition_info": False,
                                "file_url": "",
                                "hoverpic_url": None,
                                "icons_approved": True,
                                "ingredients": "",
                                "ingredients_unlocked": True,
                                "ordering_enabled": False,
                                "digest": "hash1",
                                "pos_item_id": "",
                                "synced_id": "sync1",
                                "sync_placeholder": None,
                                "tags": [],
                                "use_custom_sizes": False,
                                "food_sizes": [],
                                "ds_calories_override": "",
                                "has_subfoods": False,
                                "has_options_or_sides": False,
                                "meal_plan_price": None,
                                "nested_foods": [],
                                "nested_foods_unlocked": False,
                                "ordering_enabled_unlocked": False,
                                "synced_ingredients": "",
                                "synced_nested_foods": [],
                                "synced_ordering_enabled": False,
                                "image_alt_text": None,
                                "price": None,
                                "smart_recipe_id": None,
                                "food_highlight_message": None,
                            },
                            "no_line_break": False,
                            "blank_line": False,
                            "station_id": 1,
                            "is_station_header": False,
                            "station_is_collapsible": False,
                            "station_image_display_mode": "standard",
                            "image": "",
                            "image_thumbnail": "",
                            "serving_size_amount": None,
                            "serving_size_unit": None,
                            "smart_recipe_id": None,
                            "station_food_tags": [],
                            "food_variation_id": None,
                            "image_alt": None,
                            "image_description": None,
                            "price": None,
                        },
                        {
                            "id": 100003,
                            "position": 2,
                            "is_section_title": False,
                            "bold": False,
                            "featured": False,
                            "is_holiday": False,
                            "text": "",
                            "category": "entree",
                            "menu_id": 99,
                            "food": {
                                "id": 5002,
                                "name": "Burger",
                                "description": "Hamburger",
                                "subtext": "",
                                "image_url": None,
                                "food_category": "entree",
                                "rounded_nutrition_info": {},
                                "has_nutrition_info": False,
                                "file_url": "",
                                "hoverpic_url": None,
                                "icons_approved": True,
                                "ingredients": "",
                                "ingredients_unlocked": True,
                                "ordering_enabled": False,
                                "digest": "hash2",
                                "pos_item_id": "",
                                "synced_id": "sync2",
                                "sync_placeholder": None,
                                "tags": [],
                                "use_custom_sizes": False,
                                "food_sizes": [],
                                "ds_calories_override": "",
                                "has_subfoods": False,
                                "has_options_or_sides": False,
                                "meal_plan_price": None,
                                "nested_foods": [],
                                "nested_foods_unlocked": False,
                                "ordering_enabled_unlocked": False,
                                "synced_ingredients": "",
                                "synced_nested_foods": [],
                                "synced_ordering_enabled": False,
                                "image_alt_text": None,
                                "price": None,
                                "smart_recipe_id": None,
                                "food_highlight_message": None,
                            },
                            "no_line_break": False,
                            "blank_line": False,
                            "station_id": 1,
                            "is_station_header": False,
                            "station_is_collapsible": False,
                            "station_image_display_mode": "standard",
                            "image": "",
                            "image_thumbnail": "",
                            "serving_size_amount": None,
                            "serving_size_unit": None,
                            "smart_recipe_id": None,
                            "station_food_tags": [],
                            "food_variation_id": None,
                            "image_alt": None,
                            "image_description": None,
                            "price": None,
                        },
                        {
                            "id": 100004,
                            "position": 3,
                            "is_section_title": False,
                            "bold": False,
                            "featured": False,
                            "is_holiday": False,
                            "text": "",
                            "category": "fruit",
                            "menu_id": 99,
                            "food": {
                                "id": 5003,
                                "name": "Apple",
                                "description": "",
                                "subtext": "",
                                "image_url": None,
                                "food_category": "fruit",
                                "rounded_nutrition_info": {},
                                "has_nutrition_info": False,
                                "file_url": "",
                                "hoverpic_url": None,
                                "icons_approved": True,
                                "ingredients": "",
                                "ingredients_unlocked": True,
                                "ordering_enabled": False,
                                "digest": "hash3",
                                "pos_item_id": "",
                                "synced_id": "sync3",
                                "sync_placeholder": None,
                                "tags": [],
                                "use_custom_sizes": False,
                                "food_sizes": [],
                                "ds_calories_override": "",
                                "has_subfoods": False,
                                "has_options_or_sides": False,
                                "meal_plan_price": None,
                                "nested_foods": [],
                                "nested_foods_unlocked": False,
                                "ordering_enabled_unlocked": False,
                                "synced_ingredients": "",
                                "synced_nested_foods": [],
                                "synced_ordering_enabled": False,
                                "image_alt_text": None,
                                "price": None,
                                "smart_recipe_id": None,
                                "food_highlight_message": None,
                            },
                            "no_line_break": False,
                            "blank_line": False,
                            "station_id": 1,
                            "is_station_header": False,
                            "station_is_collapsible": False,
                            "station_image_display_mode": "standard",
                            "image": "",
                            "image_thumbnail": "",
                            "serving_size_amount": None,
                            "serving_size_unit": None,
                            "smart_recipe_id": None,
                            "station_food_tags": [],
                            "food_variation_id": None,
                            "image_alt": None,
                            "image_description": None,
                            "price": None,
                        },
                    ],
                },
            ],
        },
        "next_week": None,
    }


@pytest.fixture
def mock_nutrislice_data_validated(mock_nutrislice_data):
    """Returns the mock data already converted to Pydantic models."""
    return {
        "current_week": NutrisliceResponse.model_validate(
            mock_nutrislice_data["current_week"]
        ),
        "next_week": None,
        "previous_week": None,
    }
